### ISSUE TITLE
Can not run tests for the project

### ISSUE THREAD

**Issue by TetianaKhomenko** [cypress-io/cypress-realworld-app#1050]
Receiving `Error: Cannot find module '/Users/tania/Documents/cypress-realworld-app/aws-exports-es5.js'` when trying to run tests for the project.

NodeJS v14.17.3

Steps to reproduce:
1. clone the project from GitHub on your machine
2. open it in terminal
3. run `npm i`
4. run `npx cypress run`
5. see the error 

![image](https://user-images.githubusercontent.com/77803888/130218151-054935a2-160c-445f-be75-9e3a7a13b4b1.png)

**Comment by robertguss** [comment]
@TetianaKhomenko we are using [yarn](https://yarnpkg.com/) in this project and not npm. So please install it and then use `yarn install` to install all of the dependencies. Also, the command to run the tests is `yarn cypress:open` if you want to run Cypres with the UI. Otherwise you can use `yarn cypress:run` which will run cypress in headless mode. 

I hope that helps and solves your issue. If not, let me know.
