### ISSUE TITLE
Which way can make localhost change to local ip?

### ISSUE THREAD

**Issue by ifulltest** [cypress-io/cypress-realworld-app#1260]
Hi, team,
I can log in to http://localhost:3000 with the existed user.
But it failed when I used the same user for logging in http://192.169.199.1.:3000.
The 192.169.199.1 is my localhost IP.

May I know the exact reason?
I have tried to change localhost to 192.169.199.1 in the apiUrl, url, and baseUrl of cypress.config.js.
It seems it didn't work.

**Comment by robertguss** [comment]
@ifulltest why can't you just use localhost since that works?

**Comment by ifulltest** [comment]
@robertguss 
Yes, it works on my local windows to use the localhost.

I want to run our demo app on a CentOS/Linux system. 
So that I can monitor its system resources like CPU, memory, network, and disk, I think most of our real businesses will choose that system to be the back-end system.

In that way, we should assign the specific IP to the App on the CentOS/Linux system. And to access from our client side but not directly on the CentOS/Linux side.

**Comment by robertguss** [comment]
@ifulltest I am still not exactly sure what you are trying to do, but it is out of scope of what this project is intended for, so I can't really help you unfortunately. The real world app is for demonstration purposes only and is designed to showcase Cypress best practices. You are more than welcome to use it for another purpose since the repo is open source, but I can't provide support for something that it was not intended for. 

I hope you understand. Thank you.

**Comment by smohylevskyi** [comment]
Actually I faced the same issue today trying to deploy this demo application on one machine and running tests from the other. The API seemed available from the test machine but login was not working on UI.

I will leave my solution here just for future generations :)

I resolved this as stupid and straightforward as possible - replaced all mentions of "http://localhost:" to "http://192.168.0.104:" (local IP of machine with application running) in the whole project and rebuilt the app. The login started working on the test machine.
