### ISSUE TITLE
dockher hub node

### ISSUE THREAD

**Issue by fauzisunarya** [cypress-io/cypress-realworld-app#1564]
hello, I tried using docker hub node, when I run it it doesn't show localhost on the website, is there a solution?
![Screenshot_2024-07-15_12_56_23](https://github.com/user-attachments/assets/0fb5739f-6f3e-4611-b815-a45944545ebf)

**Comment by MikeMcC399** [comment]
@fauzisunarya 

See the Cypress documentation [Docker Prerequisites](https://docs.cypress.io/guides/getting-started/installing-cypress#Docker-Prerequisites) for information about Docker images suitable for use with Cypress.

**Comment by fauzisunarya** [comment]
@MikeMcC399 
I installed cypress-realworld-app using docker when running localhost in the browser it doesn't appear, is there a solution?

**Comment by MikeMcC399** [comment]
@fauzisunarya 

This is not really a topic for the issue list of this repo, which is for bugs and enhancement requests for the repo.

Your problem is more of a "how-to" question and Cypress offers community support for these types of questions in [![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button).

We can however try to get some clarity here if you can answer some questions:

- Are you using Desktop Docker for Mac, Linux or Windows? Or are you just using Docker Engine?
- Which exact Docker image did you use? For instance: `node`, `node:<tag>`
- Did you use a `Dockerfile` to create your own image, including Cypress dependencies?
- What command did you use to start your Docker container? `docker run ...`
