### ISSUE TITLE
How to run cypress locally inside a local Docker? 

### ISSUE THREAD

**Issue by HackPoint** [cypress-io/cypress-realworld-app#555]
My Error:
```
cypress_1  | Cypress could not verify that this server is running:
cypress_1  | 
cypress_1  |   > http://localhost:3000
cypress_1  | 
cypress_1  | We are verifying this server because it has been configured as your `baseUrl`.
cypress_1  | 
cypress_1  | Cypress automatically waits until your server is accessible before running tests.
```

My docker-compose
```version: '3.2'

# run Cypress tests and exit with command
#   docker-compose up --exit-code-from cypress
services:
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:5.0.0"
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    command: "--browser chrome"
    ports:
      - 3333:3000
    volumes:
      - ./:/e2e
```

My config
```{
  "baseUrl": "http://localhost:3000",
  "integrationFolder": "cypress/integration",
  "fileServerFolder": "dist",
  "viewportWidth": 1200,
  "viewportHeight": 1000,
  "chromeWebSecurity": true,
  "projectId": "3orb3g",
  "retries": {
    "runMode": 1,
    "openMode": 3
  }
}
```

**Comment by amirrustam** [comment]
The config in your base URL is different. It will also be helpful to provide a runnable reproduction.

**Comment by HackPoint** [comment]
> The config in your base URL is different. It will also be helpful to provide a runnable reproduction.

Thank you so much for the quick answer, but I can't create a runnable reproduction.

**Comment by HackPoint** [comment]
> The config in your base URL is different. It will also be helpful to provide a runnable reproduction.

And After I changed the Cypress baseURL it's still give's me the same issue.

**Comment by amirrustam** [comment]
Any reason you're trying to run the project in Docker? Also, can you share why you are using cypress/included:5.0.0?

**Comment by jprealini** [comment]
@HackPoint Is your local app (the one you are testing) running also in a docker container?

@amirrustam I faced the same issue, but found that since I was hitting a dockerized app and api, I had to set my baseUrl to "http://webapp/" and "http://api", instead of localhost:4001 and localhost:3000, and run my dockerized Cypress with the param --network AppNetwork (which is the docker network my app and api are using)

http://webapp and http://api are the url's that docker exposes through the AppNetwork

**Comment by amirrustam** [comment]
@HackPoint was @jprealini's suggestion helpful?

**Comment by jprealini** [comment]
@amirrustam Just a quick update here... Even though I was able to make Cypress run like that, and it opens the dockerized app correctly, I am facing a different issue now, which I suppose is related to the CORS request limitation (referenced here https://github.com/cypress-io/cypress/issues/944 ). Basically, since my api is in a different superdomain, requests made from the app in Cypress never resolve

**Comment by HackPoint** [comment]
> @HackPoint was @jprealini's suggestion helpful?

No 😢
